language: java
script: mvn clean verify
env:
  global:
  	- SONATYPE_USERNAME=mikesena
    - secure: GpgjorTGUANBmuFdhdYlfSGejwghz4d0aGE2PJzoNxb+0r6jtMQCsgi+h/Ukhn/QCwBfNn7EXxNJ76b95+mJttp/I4X7vwrnp1GvPhGU5FORkC/ot5Amz3T8MuCeql6A7/m1CgsstYagwyAm1nFpyV3CeCfJ6uShYGqt4fWnJZw=

env:
  global:
    - SONATYPE_USERNAME=yourusername
    - secure: "your encrypted SONATYPE_PASSWORD=pass"

after_success:
  - python addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml